In [1]:
import tensorflow as tf

In [2]:
print("Tensorflow version: {}".format(tf.__version__))

Tensorflow version: 2.10.0


In [3]:
v = tf.Variable(0.0)

In [4]:
(v + 1).numpy()

1.0

In [5]:
v.assign(5)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=5.0>

In [6]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [7]:
v.assign_add(1)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=6.0>

In [8]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=6.0>

In [9]:
# 将变量转换成tensor对象
v.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [10]:
w = tf.Variable([[1.0]])
# 上下文连接器
with tf.GradientTape() as t:
    loss = w * w

In [11]:
grad = t.gradient(loss, w)

In [12]:
grad

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

In [13]:
# 如果是常量的话，需要添加watch方法
w = tf.constant(3.0)
with tf.GradientTape() as t:
    t.watch(w)
    loss = w * w

In [14]:
grad = t.gradient(loss, w)

In [15]:
grad

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [16]:
# 函数嵌套的自动求解微分
w = tf.constant(3.0)
with tf.GradientTape(persistent=True) as t:
    t.watch(w)
    y = w * w
    z = y * y

In [17]:
dz_dw = t.gradient(z, w)

In [18]:
dz_dw

<tf.Tensor: shape=(), dtype=float32, numpy=108.0>