In [1]:
import tensorflow as tf

In [3]:
print("Tensorflow version: {}".format(tf.__version__))

Tensorflow version: 2.10.0


In [4]:
tf.executing_eagerly()

True

In [5]:
x = [[2, ]]

In [6]:
# 相加运算
m = tf.matmul(x, x)

In [7]:
m

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[4]])>

In [8]:
m.numpy()

array([[4]])

In [9]:
# 常量
a = tf.constant([[1, 2],[3, 4]])

In [10]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [11]:
a.numpy()

array([[1, 2],
       [3, 4]])

In [12]:
b = tf.add(a, 1)

In [13]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [14]:
import numpy as np

In [15]:
d = np.array([[5, 6], [7, 8]])

In [17]:
(a+d).numpy()

array([[ 6,  8],
       [10, 12]])

In [18]:
num = tf.convert_to_tensor(10)
num

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [19]:
for i in range(num.numpy()):
    i = tf.constant(i)
    if i%2==0:
        print("even")
    else:
        print("odd")

even
odd
even
odd
even
odd
even
odd
even
odd
