In [1]:
import tensorflow as tf

In [2]:
print("Tensorflow version: {}".format(tf.__version__))

Tensorflow version: 2.10.0


In [3]:
import numpy as np

In [5]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7, 8]))

In [6]:
dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [16]:
# 打乱顺序
dataset = dataset.shuffle(7)
# 使数组重复
dataset = dataset.repeat(count=3)
# 数组中出来的个数
dataset = dataset.batch(3)

In [17]:
for element in dataset:
    print(element.numpy())

[3 5 6]
[1 7 2]
[8 4 1]
[4 3 5]
[2 6 7]
[8 7 6]
[4 2 3]
[1 5 8]


In [18]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7, 8]))

In [19]:
# 将数组中的数据都各自平方
dataset = dataset.map(tf.square)

In [20]:
for element in dataset:
    print(element.numpy())

1
4
9
16
25
36
49
64
